#document settings
title: Federal Spending Transparency
desc: "DATA Act Collaboration Space"
url: //lpowell12.github.io/
repo_name: lpowell12.github.io
branch: master
encoding: utf-8



#global settings, no need to change these
root_url: //lpowell12.github.io
org_name: lpowell12

# default build settings for running locally, no need to edit
highlighter: rouge
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "LICENSE"]
markdown: kramdown
# markdown: redcarpet
# redcarpet:
#   extensions: []
relative_permalinks: false

gems:
 - jekyll-redirect-from

whitelist:
 - jekyll-redirect-from

navigation:
 - title: Home
   url: /index.html
 - title: Dendro
   url: /dendro
 - title: Sunburst
   url: /sunburst

sass:
  sass_dir:          assets/_scss
  #style:            :compressed

theme: jekyll-theme-slate
